api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
     #formats:
         #multipart: ['multipart/form-data']
         #jsonld:
             #mime_types:
                 #- application/ld+json
         #json:
             #mime_types:
                 #- application/json

