vich_uploader:
    db_driver: orm
    mappings:
            properties_images:
                uri_prefix: /media/properties
                upload_destination: '%kernel.project_dir%/public/media/properties'
                # Will rename uploaded files using a uniqueid as a prefix.
                namer: 
                    service: Vich\UploaderBundle\Naming\UniqidNamer

            user_images:
                uri_prefix: /media/users
                upload_destination: '%kernel.project_dir%/public/media/users'
                # Will rename uploaded files using a uniqueid as a prefix.
                namer: 
                    service: Vich\UploaderBundle\Naming\UniqidNamer

            gallery_images:
                uri_prefix: /media/interior
                upload_destination: '%kernel.project_dir%/public/media/interior'
                # Will rename uploaded files using a uniqueid as a prefix.
                namer: 
                    service: Vich\UploaderBundle\Naming\UniqidNamer


            categories_images:
                uri_prefix: /media/categories
                upload_destination: '%kernel.project_dir%/public/media/categories'
                # Will rename uploaded files using a uniqueid as a prefix.
                namer: 
                    service: Vich\UploaderBundle\Naming\UniqidNamer

                
