vich_uploader:
    db_driver: orm
    mappings:
            properties_images:
                uri_prefix: /media/properties
                upload_destination: '%kernel.project_dir%/public/media/properties'
                # Will rename uploaded files using a uniqueid as a prefix.
                namer: Vich\UploaderBundle\Naming\OrignameNamer
    
            user_images:
                uri_prefix: /media/users
                upload_destination: '%kernel.project_dir%/public/media/users'
                # Will rename uploaded files using a uniqueid as a prefix.
                namer: Vich\UploaderBundle\Naming\OrignameNamer

            gallery_images:
                uri_prefix: /media/interior
                upload_destination: '%kernel.project_dir%/public/media/interior'
                # Will rename uploaded files using a uniqueid as a prefix.
                namer: Vich\UploaderBundle\Naming\OrignameNamer

            categories_images:
                uri_prefix: /media/categories
                upload_destination: '%kernel.project_dir%/public/media/categories'
                # Will rename uploaded files using a uniqueid as a prefix.
                namer: Vich\UploaderBundle\Naming\OrignameNamer
                

                
