<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '3b1c990c4a1cd26dcff11354ab22148e',
  'DATABASE_URL' => 'mysql://root:@localhost:3306/atypikhouseapi',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
