<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '3b1c990c4a1cd26dcff11354ab22148e',
  'DATABASE_URL' => 'DATABASE_URL="mysql://root@127.0.0.1:3306/atypikhouseapi?serverVersion=mariadb-10.4.14"',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
