#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login:
   path: /api/login
   methods: [POST]

gesdinet_jwt_refresh_token:
  path:       /token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
  methods: [POST]

api_send_payment:
    path: /api/send_payment
    controller: App\Controller\SendPayment::PayoutAction
    
api_form_contact:
    path: /api/form_contact
    controller: App\Email\SendEmail::sendEmailFormContact

api_decode_JWT_Token_Auth:
    path: /api/login_check
    methods: [POST]
    controller: App\Token\DecodeJWTAuth::decodeJwtToken

api_register:
    path: /api/register
    methods: [POST]
    controller: App\Requests\Register::newUser

dashboard_owner_properties_create:
    path: /api/dashboard/owner/properties/create
    methods: [POST]
    controller: App\Requests\CreateProperties::newProperties

dashboard/admin/categories/create:
    methods: [POST]
    path: /api/dashboard/admin/categories/create
    controller: App\Requests\CreateCategories::newCategories

