#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login:
   path: /api/login
   methods: [POST]

api_send_payment:
    path: /api/send_payment
    controller: App\Controller\SendPayment::PayoutAction
    
api_form_contact:
    path: /api/form_contact
    controller: App\Email\SendEmail::sendEmailFormContact

api_decode_JWT_Token_Auth:
    path: /api/login_check
    methods: [POST]
    controller: App\Token\DecodeJWTAuth::decodeJwtToken

