#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check

api_send_payment:
    path: /api/send_payment
    controller: App\Controller\SendPayment::PayoutAction
    
#api_form_contact:
    #path: /api/form_contact
    #controller: App\Email\SendEmail::sendEmailFormContact

